### ISSUE TITLE
Pull the refs of open PRs into a set

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/deletable-branches#4]
# TODO
- [x] Implement `getRepoName(remoteUrl)`
- [x] First 100, no pagination
- [x] With pagination
  - [x] Make the existing tests use the expected query/response generators, and pass
    - [x] One test
    - [x] All tests
- [x] Edit the generators to get commits (`last` commit), too
